#!/usr/bin/env python3

from __future__ import annotations

import json
import re
from pathlib import Path


def make_label(name: str) -> str:
    return name.replace("-", " ")


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    src_json = repo_root / "third_party" / "lucide-font" / "info.json"
    out_js = repo_root / "examples" / "icon-browser" / "assets" / "lucide_browser_data.js"

    mapping = json.loads(src_json.read_text(encoding="utf-8"))
    if not isinstance(mapping, dict):
        raise ValueError("info.json root must be an object")

    items: list[dict[str, str]] = []

    for name, raw_meta in sorted(mapping.items(), key=lambda kv: kv[0]):
        meta = dict(raw_meta)
        unicode_html = str(meta.get("unicode", ""))
        match = re.search(r"(\d+)", unicode_html)
        unicode_decimal = match.group(1) if match else ""

        items.append(
            {
                "name": name,
                "label": make_label(name),
                "className": str(meta.get("className", "")),
                "prefix": str(meta.get("prefix", "")),
                "encodedCode": str(meta.get("encodedCode", "")),
                "unicode": unicode_html,
                "unicodeDecimal": unicode_decimal,
                "searchText": " ".join(
                    part.lower()
                    for part in [
                        name,
                        make_label(name),
                        str(meta.get("className", "")),
                        str(meta.get("prefix", "")),
                        unicode_decimal,
                    ]
                    if part
                ),
            }
        )

    lines: list[str] = []
    lines.append("// Generated by tools/generate_icon_browser_data.py. Do not edit manually.")
    lines.append(".pragma library")
    lines.append("")
    lines.append("var icons = ")
    lines.append(json.dumps(items, indent=4, ensure_ascii=True))
    lines.append("")
    lines.append("function allIcons() {")
    lines.append("    return icons.slice(0)")
    lines.append("}")
    lines.append("")
    lines.append("function filteredIcons(query) {")
    lines.append("    if (!query || query.length === 0)")
    lines.append("        return allIcons()")
    lines.append("")
    lines.append("    var needle = query.toLowerCase().trim()")
    lines.append("    var results = []")
    lines.append("")
    lines.append("    for (var index = 0; index < icons.length; ++index) {")
    lines.append("        var icon = icons[index]")
    lines.append("        if (icon.searchText.indexOf(needle) !== -1)")
    lines.append("            results.push(icon)")
    lines.append("    }")
    lines.append("")
    lines.append("    return results")
    lines.append("}")
    lines.append("")

    out_js.parent.mkdir(parents=True, exist_ok=True)
    out_js.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_js}")


if __name__ == "__main__":
    main()