#!/usr/bin/env python3
"""
Generate data/lucide_codepoints.js from codepoints.json.

Usage:
  python3 generate_lucide_codepoints.py
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    src_json = repo_root / "third_party" / "lucide-font" / "codepoints.json"
    data_dir = repo_root / "src" / "LucideIcons" / "data"
    out_js = data_dir / "lucide_codepoints.js"

    mapping = json.loads(src_json.read_text(encoding="utf-8"))
    if not isinstance(mapping, dict):
        raise ValueError("codepoints.json root must be an object")

    # Keep deterministic output.
    items = sorted(mapping.items(), key=lambda kv: kv[0])

    lines: list[str] = []
    lines.append("// Generated by data/generate_lucide_codepoints.py. Do not edit manually.")
    lines.append(".pragma library")
    lines.append("")
    lines.append("var map = {")

    for idx, (name, codepoint) in enumerate(items):
        cp = int(codepoint)
        comma = "," if idx < len(items) - 1 else ""
        lines.append(f'    "{name}": "\\u{cp:04x}"{comma}')

    lines.append("}")
    lines.append("")
    lines.append("function glyph(name) {")
    lines.append('        if (!name || name.length === 0)')
    lines.append('            return ""')
    lines.append("        var value = map[name]")
    lines.append('        return value !== undefined ? value : ""')
    lines.append("}")
    lines.append("")
    lines.append("function hasGlyph(name) {")
    lines.append('        if (!name || name.length === 0)')
    lines.append("            return false")
    lines.append("        return map[name] !== undefined")
    lines.append("}")
    lines.append("")
    lines.append("function names() {")
    lines.append("        return Object.keys(map)")
    lines.append("}")
    lines.append("")

    out_js.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_js}")


if __name__ == "__main__":
    main()
